# Site settings
title: joggink[dot]com
email: joggink@gmail.com
description: blogging from time to time
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joggink.com" # the base hostname & protocol for your site
twitter_username: joggink
github_username:  joggink

# Build settings
markdown: kramdown

# gems
gems:
  - jekyll-redirect-from